version: "3.7"
services:
    webapp:
        env_file: .env
        build:
            context: ./app/
            args:
                - ADMIN_USER=${HOST_ADMIN_USER}
        depends_on:
            - db
            - adminer
        image: ${WEB_APP_IMG_NAME}
        ports: 
            - "${WEB_APP_HOST_PORT}:80"
        volumes:
            - "${WEB_APP_PATH}:/var/www/html"
        networks:
            - backend 
    
    db:
        env_file: .env
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
        ports:
            - "${HOST_MYSQL_PORT}:3306"
            - "${HOST_MYSQL_PORT_SECOND}:33060" 
        volumes: 
            - "dbdata:/var/lib/mysql"
        networks:
            - backend
    
    adminer:
        env_file: .env
        image: adminer
        ports:
            - "${HOST_ADMINER_PORT}:8080"
        networks:
            - backend

    phpmyadmin:
        env_file: .env
        image: phpmyadmin/phpmyadmin
        ports:
            - "${HOST_PMA_PORT}:80"
        networks:
            - backend

volumes:
    dbdata:

networks:
    backend:
